// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ControlPlayer(arg1) {
  return window['go']['main']['App']['ControlPlayer'](arg1);
}

export function GetDeviceInfo() {
  return window['go']['main']['App']['GetDeviceInfo']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetPlaybackStatus() {
  return window['go']['main']['App']['GetPlaybackStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsWindowVisible() {
  return window['go']['main']['App']['IsWindowVisible']();
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function SetWindowTheme(arg1) {
  return window['go']['main']['App']['SetWindowTheme'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleCastService() {
  return window['go']['main']['App']['ToggleCastService']();
}
