// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ControlPlayer(arg1:string):Promise<void>;

export function GetDeviceInfo():Promise<Record<string, any>>;

export function GetLogPath():Promise<string>;

export function GetPlaybackStatus():Promise<Record<string, any>>;

export function GetSettings():Promise<config.Config>;

export function HideWindow():Promise<void>;

export function IsWindowVisible():Promise<boolean>;

export function OpenLogFolder():Promise<void>;

export function RestartApp():Promise<void>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function SetWindowTheme(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleCastService():Promise<boolean>;
